// Supported currency codes and ISO 4217 fraction digits, captured from Intl.
export const currencies = [
  { code: "AED", name: "เดอร์แฮมสหรัฐอาหรับเอมิเรตส์", digits: 2 },
  { code: "AFN", name: "อัฟกานิอัฟกานิสถาน", digits: 0 },
  { code: "ALL", name: "เลกแอลเบเนีย", digits: 0 },
  { code: "AMD", name: "แดรมอาร์เมเนีย", digits: 2 },
  { code: "ANG", name: "กิลเดอร์เนเธอร์แลนด์แอนทิลลิส", digits: 2 },
  { code: "AOA", name: "กวานซาแองโกลา", digits: 2 },
  { code: "ARS", name: "เปโซอาร์เจนตินา", digits: 2 },
  { code: "AUD", name: "ดอลลาร์ออสเตรเลีย", digits: 2 },
  { code: "AWG", name: "ฟลอรินอารูบา", digits: 2 },
  { code: "AZN", name: "มานัตอาเซอร์ไบจาน", digits: 2 },
  { code: "BAM", name: "มาร์กบอสเนีย-เฮอร์เซโกวีนา", digits: 2 },
  { code: "BBD", name: "ดอลลาร์บาร์เบโดส", digits: 2 },
  { code: "BDT", name: "ตากาบังกลาเทศ", digits: 2 },
  { code: "BGN", name: "เลฟบัลแกเรีย", digits: 2 },
  { code: "BHD", name: "ดีนาร์บาห์เรน", digits: 3 },
  { code: "BIF", name: "ฟรังก์บุรุนดี", digits: 0 },
  { code: "BMD", name: "ดอลลาร์เบอร์มิวดา", digits: 2 },
  { code: "BND", name: "ดอลลาร์บรูไน", digits: 2 },
  { code: "BOB", name: "โบลิเวียโนโบลิเวีย", digits: 2 },
  { code: "BRL", name: "เรียลบราซิล", digits: 2 },
  { code: "BSD", name: "ดอลลาร์บาฮามาส", digits: 2 },
  { code: "BTN", name: "เอ็งกุลตรัมภูฏาน", digits: 2 },
  { code: "BWP", name: "ปูลาบอตสวานา", digits: 2 },
  { code: "BYN", name: "รูเบิลเบลารุส", digits: 2 },
  { code: "BZD", name: "ดอลลาร์เบลีซ", digits: 2 },
  { code: "CAD", name: "ดอลลาร์แคนาดา", digits: 2 },
  { code: "CDF", name: "ฟรังก์คองโก", digits: 2 },
  { code: "CHF", name: "ฟรังก์สวิส", digits: 2 },
  { code: "CLP", name: "เปโซชิลี", digits: 0 },
  { code: "CNY", name: "หยวนจีน", digits: 2 },
  { code: "COP", name: "เปโซโคลอมเบีย", digits: 2 },
  { code: "CRC", name: "โกลองคอสตาริกา", digits: 2 },
  { code: "CUC", name: "เปโซคิวบา (แปลงสภาพ)", digits: 2 },
  { code: "CUP", name: "เปโซคิวบา", digits: 2 },
  { code: "CVE", name: "เอสคูโดเคปเวิร์ด", digits: 2 },
  { code: "CZK", name: "โครูนาสาธารณรัฐเช็ก", digits: 2 },
  { code: "DJF", name: "ฟรังก์จิบูตี", digits: 0 },
  { code: "DKK", name: "โครนเดนมาร์ก", digits: 2 },
  { code: "DOP", name: "เปโซโดมินิกัน", digits: 2 },
  { code: "DZD", name: "ดีนาร์แอลจีเรีย", digits: 2 },
  { code: "EGP", name: "ปอนด์อียิปต์", digits: 2 },
  { code: "ERN", name: "แนกฟาเอริเทรีย", digits: 2 },
  { code: "ETB", name: "เบอรร์เอธิโอเปีย", digits: 2 },
  { code: "EUR", name: "ยูโร", digits: 2 },
  { code: "FJD", name: "ดอลลาร์ฟิจิ", digits: 2 },
  { code: "FKP", name: "ปอนด์หมู่เกาะฟอล์กแลนด์", digits: 2 },
  { code: "GBP", name: "ปอนด์สเตอร์ลิง (สหราชอาณาจักร)", digits: 2 },
  { code: "GEL", name: "ลารีจอร์เจีย", digits: 2 },
  { code: "GHS", name: "เซดีกานา", digits: 2 },
  { code: "GIP", name: "ปอนด์ยิบรอลตาร์", digits: 2 },
  { code: "GMD", name: "ดาลาซีแกมเบีย", digits: 2 },
  { code: "GNF", name: "ฟรังก์กินี", digits: 0 },
  { code: "GTQ", name: "เควตซัลกัวเตมาลา", digits: 2 },
  { code: "GYD", name: "ดอลลาร์กายอานา", digits: 2 },
  { code: "HKD", name: "ดอลลาร์ฮ่องกง", digits: 2 },
  { code: "HNL", name: "เลมปิราฮอนดูรัส", digits: 2 },
  { code: "HRK", name: "คูนาโครเอเชีย", digits: 2 },
  { code: "HTG", name: "กูร์ดเฮติ", digits: 2 },
  { code: "HUF", name: "ฟอรินต์ฮังการี", digits: 2 },
  { code: "IDR", name: "รูเปียห์อินโดนีเซีย", digits: 2 },
  { code: "ILS", name: "นิวเชเกลอิสราเอล", digits: 2 },
  { code: "INR", name: "รูปีอินเดีย", digits: 2 },
  { code: "IQD", name: "ดีนาร์อิรัก", digits: 0 },
  { code: "IRR", name: "เรียลอิหร่าน", digits: 0 },
  { code: "ISK", name: "โครนาไอซ์แลนด์", digits: 0 },
  { code: "JMD", name: "ดอลลาร์จาเมกา", digits: 2 },
  { code: "JOD", name: "ดีนาร์จอร์แดน", digits: 3 },
  { code: "JPY", name: "เยนญี่ปุ่น", digits: 0 },
  { code: "KES", name: "ชิลลิงเคนยา", digits: 2 },
  { code: "KGS", name: "ซอมคีร์กีซสถาน", digits: 2 },
  { code: "KHR", name: "เรียลกัมพูชา", digits: 2 },
  { code: "KMF", name: "ฟรังก์คอโมโรส", digits: 0 },
  { code: "KPW", name: "วอนเกาหลีเหนือ", digits: 0 },
  { code: "KRW", name: "วอนเกาหลีใต้", digits: 0 },
  { code: "KWD", name: "ดีนาร์คูเวต", digits: 3 },
  { code: "KYD", name: "ดอลลาร์หมู่เกาะเคย์แมน", digits: 2 },
  { code: "KZT", name: "เทงเจคาซัคสถาน", digits: 2 },
  { code: "LAK", name: "กีบลาว", digits: 0 },
  { code: "LBP", name: "ปอนด์เลบานอน", digits: 0 },
  { code: "LKR", name: "รูปีศรีลังกา", digits: 2 },
  { code: "LRD", name: "ดอลลาร์ไลบีเรีย", digits: 2 },
  { code: "LSL", name: "โลตีเลโซโท", digits: 2 },
  { code: "LYD", name: "ดีนาร์ลิเบีย", digits: 3 },
  { code: "MAD", name: "ดีแรห์มโมร็อกโก", digits: 2 },
  { code: "MDL", name: "ลิวมอลโดวา", digits: 2 },
  { code: "MGA", name: "อาเรียรีมาลากาซี", digits: 0 },
  { code: "MKD", name: "ดีนาร์มาซิโดเนีย", digits: 2 },
  { code: "MMK", name: "จ๊าตพม่า", digits: 0 },
  { code: "MNT", name: "ทูกริกมองโกเลีย", digits: 2 },
  { code: "MOP", name: "ปาตากามาเก๊า", digits: 2 },
  { code: "MRU", name: "อูกียามอริเตเนีย", digits: 2 },
  { code: "MUR", name: "รูปีมอริเชียส", digits: 2 },
  { code: "MVR", name: "รูฟิยามัลดีฟส์", digits: 2 },
  { code: "MWK", name: "ควาชามาลาวี", digits: 2 },
  { code: "MXN", name: "เปโซเม็กซิโก", digits: 2 },
  { code: "MYR", name: "ริงกิตมาเลเซีย", digits: 2 },
  { code: "MZN", name: "เมติคัลโมซัมบิก", digits: 2 },
  { code: "NAD", name: "ดอลลาร์นามิเบีย", digits: 2 },
  { code: "NGN", name: "ไนราไนจีเรีย", digits: 2 },
  { code: "NIO", name: "กอร์โดบานิการากัว", digits: 2 },
  { code: "NOK", name: "โครนนอร์เวย์", digits: 2 },
  { code: "NPR", name: "รูปีเนปาล", digits: 2 },
  { code: "NZD", name: "ดอลลาร์นิวซีแลนด์", digits: 2 },
  { code: "OMR", name: "เรียลโอมาน", digits: 3 },
  { code: "PAB", name: "บัลบัวปานามา", digits: 2 },
  { code: "PEN", name: "ซอลเปรู", digits: 2 },
  { code: "PGK", name: "กีนาปาปัวนิวกินี", digits: 2 },
  { code: "PHP", name: "เปโซฟิลิปปินส์", digits: 2 },
  { code: "PKR", name: "รูปีปากีสถาน", digits: 2 },
  { code: "PLN", name: "ซลอตีโปแลนด์", digits: 2 },
  { code: "PYG", name: "กวารานีปารากวัย", digits: 0 },
  { code: "QAR", name: "เรียลกาตาร์", digits: 2 },
  { code: "RON", name: "ลิวโรมาเนีย", digits: 2 },
  { code: "RSD", name: "ดีนาร์เซอร์เบีย", digits: 0 },
  { code: "RUB", name: "รูเบิลรัสเซีย", digits: 2 },
  { code: "RWF", name: "ฟรังก์รวันดา", digits: 0 },
  { code: "SAR", name: "ริยัลซาอุดีอาระเบีย", digits: 2 },
  { code: "SBD", name: "ดอลลาร์หมู่เกาะโซโลมอน", digits: 2 },
  { code: "SCR", name: "รูปีเซเชลส์", digits: 2 },
  { code: "SDG", name: "ปอนด์ซูดาน", digits: 2 },
  { code: "SEK", name: "โครนาสวีเดน", digits: 2 },
  { code: "SGD", name: "ดอลลาร์สิงคโปร์", digits: 2 },
  { code: "SHP", name: "ปอนด์เซนต์เฮเลนา", digits: 2 },
  { code: "SLE", name: "ลีโอนเซียร์ราลีโอน", digits: 2 },
  { code: "SLL", name: "ลีโอนเซียร์ราลีโอน (1964—2022)", digits: 0 },
  { code: "SOS", name: "ชิลลิงโซมาเลีย", digits: 0 },
  { code: "SRD", name: "ดอลลาร์ซูรินาเม", digits: 2 },
  { code: "SSP", name: "ปอนด์ซูดานใต้", digits: 2 },
  { code: "STN", name: "ดอบราเซาตูเมและปรินซิปี", digits: 2 },
  { code: "SVC", name: "โคลอนเอลซัลวาดอร์", digits: 2 },
  { code: "SYP", name: "ปอนด์ซีเรีย", digits: 0 },
  { code: "SZL", name: "ลิลันเจนีสวาซิ", digits: 2 },
  { code: "THB", name: "บาท", digits: 2 },
  { code: "TJS", name: "โซโมนิทาจิกิสถาน", digits: 2 },
  { code: "TMT", name: "มานัตเติร์กเมนิสถาน", digits: 2 },
  { code: "TND", name: "ดีนาร์ตูนิเซีย", digits: 3 },
  { code: "TOP", name: "พาแองกาตองกา", digits: 2 },
  { code: "TRY", name: "ลีราตุรกี", digits: 2 },
  { code: "TTD", name: "ดอลลาร์ตรินิแดดและโตเบโก", digits: 2 },
  { code: "TWD", name: "ดอลลาร์ไต้หวันใหม่", digits: 2 },
  { code: "TZS", name: "ชิลลิงแทนซาเนีย", digits: 2 },
  { code: "UAH", name: "ฮรีฟเนียยูเครน", digits: 2 },
  { code: "UGX", name: "ชิลลิงยูกันดา", digits: 0 },
  { code: "USD", name: "ดอลลาร์สหรัฐ", digits: 2 },
  { code: "UYU", name: "เปโซอุรุกวัย", digits: 2 },
  { code: "UZS", name: "ซอมอุซเบกิสถาน", digits: 2 },
  { code: "VES", name: "โบลีวาร์เวเนซุเอลา", digits: 2 },
  { code: "VND", name: "ดองเวียดนาม", digits: 0 },
  { code: "VUV", name: "วาตูวานูอาตู", digits: 0 },
  { code: "WST", name: "ทาลาซามัว", digits: 2 },
  { code: "XAF", name: "ฟรังก์เซฟาธนาคารรัฐแอฟริกากลาง", digits: 0 },
  { code: "XCD", name: "ดอลลาร์แคริบเบียนตะวันออก", digits: 2 },
  { code: "XCG", name: "XCG", digits: 2 },
  { code: "XDR", name: "สิทธิถอนเงินพิเศษ", digits: 2 },
  { code: "XOF", name: "ฟรังก์เซฟาธนาคารกลางรัฐแอฟริกาตะวันตก", digits: 0 },
  { code: "XPF", name: "ฟรังก์ซีเอฟพี", digits: 0 },
  { code: "XSU", name: "ซูเกร", digits: 2 },
  { code: "YER", name: "เรียลเยเมน", digits: 0 },
  { code: "ZAR", name: "แรนด์แอฟริกาใต้", digits: 2 },
  { code: "ZMW", name: "ควาชาแซมเบีย", digits: 2 },
  { code: "ZWG", name: "ZWG", digits: 2 },
  { code: "ZWL", name: "ดอลลาร์ซิมบับเว (2009)", digits: 2 },
] as const;

export type Currency = (typeof currencies)[number]["code"];

export const currencyOptions = currencies.map(({ code, name }) => ({
  value: code,
  label: `${code} — ${name}`,
}));

const currencyByCode = new Map<string, (typeof currencies)[number]>(
  currencies.map((currency) => [currency.code, currency]),
);

export function isCurrency(value: unknown): value is Currency {
  return typeof value === "string" && currencyByCode.has(value);
}

export function getCurrencyDigits(currency: Currency) {
  return currencyByCode.get(currency)!.digits;
}

export function getCurrencyLabel(currency: Currency) {
  const entry = currencyByCode.get(currency)!;
  return `${entry.name} (${currency})`;
}
